services:
  ploigi-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ploigi-web-container
    ports:
      - "3000"
    restart: always
    env_file:
      - .env.production

    # depends_on:
    #   - ploigi-dev-mock

  # ploigi-dev-mock:
  #   build: ../ploigi-dev
  #   ports:
  #     - "8000:8000"