services:
  ploigi-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ploigi-web-container
    ports:
      - target: 3000        # コンテナ内部のポート
        published: 3000     # ホスト（VPS）側のポート
        host_ip: 127.0.0.1  # 🔒 ローカルホスト（内部通信）だけに縛る設定
        mode: host
    restart: always
    env_file:
      - .env.production
    environment:
      - HOSTNAME=0.0.0.0
    # depends_on:
    #   - ploigi-dev-mock

  # ploigi-dev-mock:
  #   build: ../ploigi-dev
  #   ports:
  #     - "8000:8000"
